name: Deploy to ECS

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAUEOQB3Y2BYID5SFF
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 284441042484.dkr.ecr.us-east-1.amazonaws.com
           env:
                 AWS_DEFAULT_REGION: us-east-1
                 AWS_REGION: us-east-1


      - name: Build Docker image
        run: docker build -t my-python-app .

      - name: Tag Docker image
        run: docker tag my-python-app:latest 284441042484.dkr.ecr.us-east-1.amazonaws.com/my-python-app:latest

      - name: Push Docker image to Amazon ECR
        run: docker push 284441042484.dkr.ecr.us-east-1.amazonaws.com/my-python-app:latest
